{{- if Values.governedRunner.enabled }}
{{- $Values := .Values -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-governed-runner
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-governed-runner
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-governed-runner
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: app
        image: gcr.io/rdm-test-01/governed-runner:0.0.2
        ports:
        - containerPort: 18000
        command:
        - --host
        - 0.0.0.0
        - --port
        - "18000"
{{- end }}
