#!/bin/sh
# Use https://www.shellcheck.net/ to reduce mistakes if you make changes to this file.

set -x

await_jupyterhub() {
    kubectl rollout status --watch --timeout 300s deployment/proxy \
 && kubectl-argo-rollouts status --watch --timeout 300s hub \
 && (
        if kubectl get deploy/autohttps > /dev/null 2>&1; then
            kubectl rollout status --watch --timeout 300s deployment/autohttps
        fi
    )
}

await_binderhub() {
    # accepts the release name as a parameter
    await_jupyterhub
    kubectl-argo-rollouts status --watch --timeout 300s binder
}
